apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: workshop
  name: arseni-http-doom
  labels:
    app: arseni-http-doom

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: arseni-http-doom

  template:
    metadata:
      labels:
        app: arseni-http-doom
      annotations:
    spec:
      containers:
        - image: docker.io/arsenileskinen/http-doom:master
          name: arseni-http-doom
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: SOME_ENV_VARIABLE
              value: some env value

      nodeSelector:
        cloud.google.com/gke-nodepool: workshop-pool
